---
name: Kaniko Build
on:
  workflow_dispatch:
    inputs:
      registry:
        type: choice
        description: Target registry
        default: ghcr.io
        options:
          - ghcr.io
          - scr.cd43.sthings-pve.labul.sva.de
      repository:
        type: choice
        description: Target repository
        default: stuttgart-things/kaeffken
        options:
          - stuttgart-things/sthings-slides
      image:
        type: string
        description: Image name
        default: kaeffken
      tag:
        type: string
        description: Image tag       
        
jobs:
  Build-Kaniko-Image:
    name: Build Kaniko
    uses: stuttgart-things/stuttgart-things/.github/workflows/build-kaniko.yaml@main
    with:
      environment-name: k8s
      runs-on: arc-runner-scale-set-sthings-slides
      dockerfile: ./Dockerfile
      registry: "${{ github.event.inputs.registry }}"
      repository: "${{ github.event.inputs.repository }}"  
      image: "${{ github.event.inputs.image }}" 
      tag: "${{ github.event.inputs.tag }}"
    secrets: inherit
