---
name: Kaniko Build
on:
  workflow_dispatch:
  #push:
   # branches:
    #  - main

jobs:
  kaniko:
    environment: k8s
    runs-on: arc-runner-scale-set-sthings-slides
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: aevea/kaniko
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          cache: true
          cache_registry: aevea/cache
