---
name: Validate-Golang
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
      - review/*
      - fix/*
  pull_request:
    types: [opened, reopened]

jobs:
  Validate-Golang-Code:
    name: Valdiate Golang
    uses: stuttgart-things/stuttgart-things/.github/workflows/validate-golang.yaml@main
    with:
      module-name: sthingsslides
      environment-name: k8s
      runs-on: arc-runner-scale-set-sthings-slides
      golint-version: v1.55
      golang-version: "1.21.5"
      accept-linterrors: true
      accept-failedtests: true

  Build-Kaniko-Image:
    name: Build Kaniko
    needs: validate-golang
    uses: stuttgart-things/stuttgart-things/.github/workflows/build-kaniko.yaml@main
    with:
      environment-name: k8s
      runs-on: arc-runner-scale-set-sthings-slides
      dockerfile: ./Dockerfile
      registry: ghcr.io
      repository: stuttgart-things/sthings-slides  
      image: sthings-slides
      tag: ""
    secrets: inherit
